{% set name = "megmap" %}
{% set version = "0.0.1A" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/husonlab/megmap/archive/{{version}}.tar.gz
  # git_url: https://github.com/husonlab/megmap.git
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies

requirements:
  host:
    - python ==3.10.0
    - setuptools
    - pip
  run:
    - python  ==3.10.0
    - diamond ==2.0.15
    - ete3 ==3.1.2
    - numpy ==1.23.0
    - pandas ==1.4.4
    - blast ==2.12.0
    - filetype ==1.0.7


about:
  home: https://github.com/husonlab/megmap.git
  license: GPL-3.0 License
  license_family: GPL
  license_file: LICENSE
  summary: Metagenome mapping utilities
  description: |
    megmap help you perform metagenomic analysis against special purpose database.
